# Generated by Django 6.0.5 on 2026-05-20 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(unique=True, verbose_name='회차')),
                ('number1', models.PositiveIntegerField(verbose_name='당첨번호 1')),
                ('number2', models.PositiveIntegerField(verbose_name='당첨번호 2')),
                ('number3', models.PositiveIntegerField(verbose_name='당첨번호 3')),
                ('number4', models.PositiveIntegerField(verbose_name='당첨번호 4')),
                ('number5', models.PositiveIntegerField(verbose_name='당첨번호 5')),
                ('number6', models.PositiveIntegerField(verbose_name='당첨번호 6')),
                ('bonus_number', models.PositiveIntegerField(verbose_name='보너스 번호')),
                ('drawn_at', models.DateTimeField(auto_now_add=True, verbose_name='추첨 일시')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=50, verbose_name='구매자 이름')),
                ('number1', models.PositiveIntegerField(verbose_name='선택한 번호 1')),
                ('number2', models.PositiveIntegerField(verbose_name='선택한 번호 2')),
                ('number3', models.PositiveIntegerField(verbose_name='선택한 번호 3')),
                ('number4', models.PositiveIntegerField(verbose_name='선택한 번호 4')),
                ('number5', models.PositiveIntegerField(verbose_name='선택한 번호 5')),
                ('number6', models.PositiveIntegerField(verbose_name='선택한 번호 6')),
                ('purchase_type', models.CharField(choices=[('manual', '수동'), ('auto', '자동')], max_length=10, verbose_name='구매 방식')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='구매 날짜')),
                ('draw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='lotto.draw', verbose_name='추첨 회차')),
            ],
        ),
        migrations.CreateModel(
            name='WinningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_count', models.PositiveIntegerField(verbose_name='일치 개수')),
                ('bonus_matched', models.BooleanField(default=False, verbose_name='보너스 번호 일치 여부')),
                ('rank', models.CharField(choices=[('1등', '1등'), ('2등', '2등'), ('3등', '3등'), ('4등', '4등'), ('5등', '5등'), ('낙첨', '낙첨')], max_length=10, verbose_name='당첨 등수')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='확인 일시')),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winning_results', to='lotto.draw', verbose_name='추첨 회차')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winning_result', to='lotto.ticket', verbose_name='구매 티켓')),
            ],
        ),
    ]
